# Generated by Django 5.2 on 2025-05-06 16:05

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('current_visit_date', django_jalali.db.models.jDateField(verbose_name='تاریخ ویزیت')),
                ('next_visit_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ویزیت بعدی')),
                ('SMS_sent', models.BooleanField(default=False, verbose_name='پیامک داده شده')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.service', verbose_name=' خدمات')),
            ],
        ),
    ]
