# Generated by Django 5.2.1 on 2025-05-09 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('same_day_reminder_hour', models.IntegerField(default=8, help_text='ساعت ارسال پیامک یادآوری در روز ویزیت (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='ساعت ارسال پیامک یادآوری روز ویزیت')),
                ('day_before_reminder_hour', models.IntegerField(default=20, help_text='ساعت ارسال پیامک یادآوری در روز قبل از ویزیت (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='ساعت ارسال پیامک یادآوری روز قبل')),
                ('is_active', models.BooleanField(default=True, help_text='آیا ارسال پیامک فعال باشد؟', verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات پیامک',
                'verbose_name_plural': 'تنظیمات پیامک',
            },
        ),
    ]
