services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 3 --reload --reload-engine auto
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DATABASE_URL=postgres://app_user:app_password@db:5432/app_db
      - RABBITMQ_URL=amqp://app_user:app_password@rabbitmq:5672//
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: always

  celery:
    build: .
    command: celery -A myproject worker -l INFO
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DATABASE_URL=postgres://app_user:app_password@db:5432/app_db
      - RABBITMQ_URL=amqp://app_user:app_password@rabbitmq:5672//
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - web
      - rabbitmq
    restart: always

  celery-beat:
    build: .
    command: celery -A myproject beat -l INFO
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DATABASE_URL=postgres://app_user:app_password@db:5432/app_db
      - RABBITMQ_URL=amqp://app_user:app_password@rabbitmq:5672//
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - web
      - rabbitmq
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=app_user
      - RABBITMQ_DEFAULT_PASS=app_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  postgres_data:
    external: true
  rabbitmq_data:
    external: true
  static_volume:
  media_volume:
     

